"""baseline schema

Revision ID: aa29cbb73f73
Revises: 
Create Date: 2026-03-01 11:02:23.280284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa29cbb73f73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS calendar")
    op.execute("CREATE SCHEMA IF NOT EXISTS evaluations")
    op.execute("CREATE SCHEMA IF NOT EXISTS identity")
    op.execute("CREATE SCHEMA IF NOT EXISTS scheduling")
    op.execute("CREATE SCHEMA IF NOT EXISTS tasks")
    op.execute("CREATE SCHEMA IF NOT EXISTS teams")

    op.create_table('calendar_user',
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_dttm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_dttm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='calendar'
    )
    op.create_table('evaluations_task',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.Column('executor_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'DONE', name='evaluations_task_status'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_dttm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_dttm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='evaluations'
    )
    op.create_table('evaluations_user',
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_dttm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_dttm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='evaluations'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_users_deleted'), 'users', ['deleted'], unique=False, schema='identity')
    op.create_index(op.f('ix_identity_users_email'), 'users', ['email'], unique=True, schema='identity')
    op.create_table('scheduling_team',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_dttm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_dttm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='scheduling'
    )
    op.create_table('scheduling_user',
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_dttm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_dttm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='scheduling'
    )
    op.create_table('tasks_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_dttm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_dttm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='tasks'
    )
    op.create_table('tasks_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('created_dttm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_dttm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='tasks'
    )
    op.create_table('teams',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_dttm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_dttm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='teams'
    )
    op.create_table('teams_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('created_dttm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_dttm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='teams'
    )
    op.create_table('calendar_event',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('MEETING', 'TASK', name='calendar_event_type'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('cancelled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_dttm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_dttm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['calendar.calendar_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_type', 'reference_id', name='uq_calendar_event_user_type_reference'),
    schema='calendar'
    )
    op.create_table('evaluations',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_dttm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_dttm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['evaluations.evaluations_task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['evaluations.evaluations_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='evaluations'
    )
    op.create_table('scheduling_meeting',
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_dttm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_dttm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organizer_id'], ['scheduling.scheduling_user.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['scheduling.scheduling_team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='scheduling'
    )
    op.create_table('scheduling_member',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('is_manager', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_dttm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_dttm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['scheduling.scheduling_team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['scheduling.scheduling_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='scheduling'
    )
    op.create_table('tasks',
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.Column('executor_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'DONE', name='tasks_status'), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_dttm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_dttm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['executor_id'], ['tasks.tasks_user.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['tasks.tasks_user.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['tasks.tasks_teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tasks'
    )
    op.create_table('tasks_member',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['tasks.tasks_teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tasks.tasks_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tasks'
    )
    op.create_table('teams_members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['teams.teams_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='teams'
    )
    op.create_table('scheduling_meeting_participant',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_dttm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_dttm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['scheduling.scheduling_meeting.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['scheduling.scheduling_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='scheduling'
    )
    op.create_table('tasks_comment',
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_dttm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_dttm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['tasks.tasks_user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.tasks.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['tasks.tasks_teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tasks'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks_comment', schema='tasks')
    op.drop_table('scheduling_meeting_participant', schema='scheduling')
    op.drop_table('teams_members', schema='teams')
    op.drop_table('tasks_member', schema='tasks')
    op.drop_table('tasks', schema='tasks')
    op.drop_table('scheduling_member', schema='scheduling')
    op.drop_table('scheduling_meeting', schema='scheduling')
    op.drop_table('evaluations', schema='evaluations')
    op.drop_table('calendar_event', schema='calendar')
    op.drop_table('teams_user', schema='teams')
    op.drop_table('teams', schema='teams')
    op.drop_table('tasks_user', schema='tasks')
    op.drop_table('tasks_teams', schema='tasks')
    op.drop_table('scheduling_user', schema='scheduling')
    op.drop_table('scheduling_team', schema='scheduling')
    op.drop_index(op.f('ix_identity_users_email'), table_name='users', schema='identity')
    op.drop_index(op.f('ix_identity_users_deleted'), table_name='users', schema='identity')
    op.drop_table('users', schema='identity')
    op.drop_table('evaluations_user', schema='evaluations')
    op.drop_table('evaluations_task', schema='evaluations')
    op.drop_table('calendar_user', schema='calendar')
    op.execute("DROP SCHEMA IF EXISTS teams")
    op.execute("DROP SCHEMA IF EXISTS tasks")
    op.execute("DROP SCHEMA IF EXISTS scheduling")
    op.execute("DROP SCHEMA IF EXISTS identity")
    op.execute("DROP SCHEMA IF EXISTS evaluations")
    op.execute("DROP SCHEMA IF EXISTS calendar")
    # ### end Alembic commands ###
